###############################################################################
# Sloan Digital Sky Survey (SDSS) -- PHOTO Operations
# D. Finkbeiner & D. Schlegel
###############################################################################

SHELL = /bin/sh

all :;

install :
	- cp * $(EUPS_DIR)/etc

clean :
	- /bin/rm -f *~ core
