###############################################################################
# Sloan Digital Sky Survey (SDSS) -- PHOTO Operations
# N. Padmanabhan, D. Schlegel, & D. Finkbeiner
###############################################################################

SHELL = /bin/sh

all :;

install :
	- cp Makefile current.chain example.table example.version $(EUPS_DIR)/examples
clean :
	- /bin/rm -f *~ core
