###############################################################################
# Sloan Digital Sky Survey (SDSS) -- PHOTO Operations
# D. Finkbeiner & D. Schlegel
###############################################################################

SHELL = /bin/sh
#
all :;
#
# Install things in their proper places in $(PHOTOOP_DIR)
#
install :
	- cp * $(EUPS_DIR)/examples

clean :
	- /bin/rm -f *~ core
